version: 2
jobs:
  build:

    # Primary container image where all commands run

    docker:
      - image: circleci/node:10.8.0-browsers
        environment:
          NODE_ENV: test
          PG_PASS:
          PG_HOST: localhost
          PG_DB: canchas_test

      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: yarn recreate-test-db
      - run: yarn install
      - run: yarn test
